name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Mohideen2005
          outputs: output/github-contribution-grid-snake.svg
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update snake animation SVG"
          file_pattern: output/*.svg
          push_options: --force
